version: "3.9"

services:
  client:
    build: client/
    volumes:
      - ./client:/home/app
      - /home/app/node_modules
    ports:
      - "80:8080"
    depends_on:
      - server

  server:
    build: server/
    volumes:
      - ./server:/home/app
      - /home/app/node_modules
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
