version: "3.9"

services:
  client:
    build: client/
    volumes:
      - ./client:/home/app
      - /home/app/node_modules
    ports:
      - "80:8080"
    depends_on:
      - server

  server:
    # image: node:16-alpine
    build: server/
    volumes:
      - ./server:/home/app
      - /home/app/node_modules
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_HOST: db
      DB_PORT: 5432
    # volumes:
      # - .:/var/www/html
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16
    # volumes:
    #   - ./docker/db/dump.tar:/var/lib/postgresql/dump.tar
    #   - ./docker/db/init.sh:/docker-entrypoint-initdb.d/init.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
